sudo: false
addons:
  apt:
    packages:
      - omniidl
      # - g++-6
matrix:
  allow_failures:
    - python: 3.8-dev
  include:
    - language: python
      python: 3.6
    - language: python
      dist: xenial
      python: 3.7
    - language: python
      dist: xenial
      python: 3.8-dev

before_install:
  # Avoids certain compilation issues.
  - 'export CCFLAGS="-std=c++11"'
  - 'export CXXFLAGS="-std=c++11"'
install:
  - pip install -U pip setuptools coverage flake8
  - pip install zc.buildout
  - buildout
  - 'pip install -I --global-option="build_ext" --global-option="-I$(pwd)/parts/cellml-api/include" --global-option="-L$(pwd)/parts/cellml-api/lib:$(pwd)/parts/cellml-api/lib/cgrs_modules" --global-option="-R$(pwd)/parts/cellml-api/lib:$(pwd)/parts/cellml-api/lib/cgrs_modules" cgrspy'
  - pip install -e .

script:
  - flake8 setup.py src
  - coverage run --include=src/* -m unittest repodono.cellml.tests.make_suite
  - coverage report -m
after_success:
  - pip install coveralls
  - coveralls
branches:
  only:
    - testing
    - master
    - 1.0.x
